In [4]:
import pandas as pd
import numpy as np
import random as rand

In [5]:
state_zero = [['w','','w','','w','','w',''],
              ['','w','','w','','w','','w'],
              ['w','','w','','w','','w',''],
              ['','','','','','','',''],
              ['','','','','','','',''],
              ['','b','','b','','b','','b'],
              ['b','','b','','b','','b',''],
              ['','b','','b','','b','','b']
             ]

In [6]:
def resetBoard():
    global board_state
    board_state = pd.DataFrame(state_zero,index=range(0,8),columns=range(0,8))
    return board_state
resetBoard()

   0  1  2  3  4  5  6  7
0  w     w     w     w
1     w     w     w     w
2  w     w     w     w
3
4
5     b     b     b     b
6  b     b     b     b
7     b     b     b     b

In [7]:
# Finds the location of pieces on a board

def pieceFinder(color):
    pieceLoc = []
    for column in np.arange(0,8,1):
        for row in np.arange(0,8,1):
            if board_state.iloc[row,column] == color:
                pieceLoc += [[row,column]]
    return pieceLoc

In [15]:
def blackMove():
    pieceCount = len(pieceFinder('b'))
    isTurn = True

    while isTurn == True:
        for piece in np.arange(0,pieceCount,1):
            row = pieceFinder('b')[piece][0]
            column = pieceFinder('b')[piece][1]
            try: 
                # Right diagonal movement
                if board_state.iloc[row-1,column+1] == '':
                    board_state.iloc[row-1,column+1] = 'b'
                    board_state.iloc[row,column] = ''
                    display(board_state)
                    isTurn = False
                    break
                # Left diagonal movement
                elif board_state.iloc[row-1,column-1] == '':
                    board_state.iloc[row-1,column-1] = 'b'
                    board_state.iloc[row,column] = ''
                    display(board_state)
                    isTurn = False
                    break
                # if the left diagonal square has a white piece and the diagonal after is empty, jump and capture the piece
                elif board_state.iloc[row-1,column+1] == 'w' & board_state.iloc[row-2,column+2]=='':
                    board_state.iloc[row-2,column+2] = 'b'
                    board_state.iloc[row,column] = ''
                    board_state.iloc[row-1,column+1] = ''
                    display(board_state)
                    isTurn = False
                    break
                #right diagonal
                elif board_state.iloc[row-1,column-1] == 'w' & board_state.iloc[row-2,column-2]=='':
                    board_state.iloc[row-2,column-2] = 'b'
                    board_state.iloc[row,column] = ''
                    board_state.iloc[row-1,column+1] = ''
                    display(board_state)
                    isTurn = False
                    break
                      
                else:
                    print("Piece unable to move\n")


            except: 
                print("Cannot Find a Legal Move.")

In [16]:
def whiteMove():
    pieceCount = len(pieceFinder('w'))
    isTurn = True
    while isTurn == True:
#         Find a Piece on the board to move
        for piece in np.arange(0,pieceCount,1):
            row = pieceFinder('w')[piece][0]
            column = pieceFinder('w')[piece][1]
#             Implement a method of selecting a strategy after a piece has been selected
            try: 
                elif board_state.iloc[row+1,column+1] == '':
                    board_state.iloc[row+1,column+1] = 'w'
                    board_state.iloc[row,column] = ''
                    display(board_state)
                    isTurn = False
                    break

                elif board_state.iloc[row+1,column-1] == '':
                    board_state.iloc[row+1,column-1] = 'w'
                    board_state.iloc[row,column] = ''
                    display(board_state)
                    isTurn = False
                    break
                # if the left diagonal square has a white piece and the diagonal after is empty, jump and capture the piece
                elif board_state.iloc[row+1,column+1] == 'b' & board_state.iloc[row+2,column+2]=='':
                    board_state.iloc[row+2,column+2] = 'w'
                    board_state.iloc[row,column] = ''
                    board_state.iloc[row+1,column+1] = ''
                    display(board_state)
                    isTurn = False
                    break
                #right diagonal
                elif board_state.iloc[row+1,column-1] == 'b' & board_state.iloc[row+2,column-2]=='':
                    board_state.iloc[row+2,column-2] = 'w'
                    board_state.iloc[row,column] = ''
                    board_state.iloc[row+1,column-1] = ''
                    display(board_state)
                    isTurn = False
                    break

                else:
                    print("Piece unable to move\n")


            except: 
                print("Cannot Find a Legal Move.")

In [21]:

resetBoard()
for i in np.arange(0,3,1):
    if i % 2 == 0:
        blackMove()
    else:
        whiteMove()

Cannot Find a Legal Move.

   0  1  2  3  4  5  6  7
0  w     w     w     w
1     w     w     w     w
2  w     w     w     w
3
4        b
5           b     b     b
6  b     b     b     b
7     b     b     b     b

Cannot Find a Legal Move.

   0  1  2  3  4  5  6  7
0  w     w     w     w
1     w     w     w     w
2        w     w     w
3     w
4        b
5           b     b     b
6  b     b     b     b
7     b     b     b     b

   0  1  2  3  4  5  6  7
0  w     w     w     w
1     w     w     w     w
2        w     w     w
3     w
4        b
5     b     b     b     b
6        b     b     b
7     b     b     b     b

In [19]:
resetBoard()

   0  1  2  3  4  5  6  7
0  w     w     w     w
1     w     w     w     w
2  w     w     w     w
3
4
5     b     b     b     b
6  b     b     b     b
7     b     b     b     b